development:
  adapter: postgresql
  encoding: unicode
  database: url_shortner_development
  pool: 5
  username: postgres
  password: bhanu

test:
  adapter: postgresql
  encoding: unicode
  database: url_shortner_test
  pool: 5
  username: postgres
  password: bhanu

production:
  adapter: postgresql
  encoding: unicode
  database: url_shortner_production
  pool: 5
  username:
  password: